/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Principal;
export const MessageId = IDL.Nat;
export const Timestamp = IDL.Int;
export const AdminMessagePublic = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'isRead' : IDL.Bool,
  'sender' : UserId,
  'sentAt' : Timestamp,
  'isAdminReply' : IDL.Bool,
});
export const ReportId = IDL.Nat;
export const ReportStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'pending' : IDL.Null,
  'approved' : IDL.Null,
});
export const ReportCategory = IDL.Variant({
  'other' : IDL.Null,
  'garbage' : IDL.Null,
  'unsafe' : IDL.Null,
  'pollution' : IDL.Null,
});
export const ReportPublic = IDL.Record({
  'id' : ReportId,
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'status' : ReportStatus,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'photoUrl' : IDL.Text,
  'category' : ReportCategory,
  'reporter' : UserId,
});
export const BadgeId = IDL.Variant({
  'pioneer' : IDL.Null,
  'hundred_reports' : IDL.Null,
  'ten_reports' : IDL.Null,
  'first_report' : IDL.Null,
  'fifty_reports' : IDL.Null,
  'eco_warrior' : IDL.Null,
});
export const BadgeMetadata = IDL.Record({
  'id' : BadgeId,
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'milestone' : IDL.Text,
});
export const ChatId = IDL.Text;
export const ChatMessagePublic = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'isRead' : IDL.Bool,
  'sender' : UserId,
  'sentAt' : Timestamp,
  'chatId' : ChatId,
});
export const ChatPreview = IDL.Record({
  'lastMessageAt' : Timestamp,
  'otherUsername' : IDL.Text,
  'otherUserId' : UserId,
  'lastMessage' : IDL.Text,
  'unreadCount' : IDL.Nat,
  'chatId' : ChatId,
});
export const HeatmapPoint = IDL.Record({
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'weight' : IDL.Nat,
});
export const LeaderboardEntry = IDL.Record({
  'username' : IDL.Text,
  'userId' : UserId,
  'rank' : IDL.Nat,
  'badgeCount' : IDL.Nat,
  'points' : IDL.Nat,
});
export const UserProfilePublic = IDL.Record({
  'id' : UserId,
  'reportCount' : IDL.Nat,
  'username' : IDL.Text,
  'badges' : IDL.Vec(BadgeId),
  'joinedAt' : Timestamp,
  'avatarUrl' : IDL.Opt(IDL.Text),
  'points' : IDL.Nat,
});
export const SubmitReportArgs = IDL.Record({
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'description' : IDL.Text,
  'photoUrl' : IDL.Text,
  'category' : ReportCategory,
});

export const idlService = IDL.Service({
  'adminReply' : IDL.Func([UserId, IDL.Text], [MessageId], []),
  'getAdminInbox' : IDL.Func([], [IDL.Vec(UserId)], ['query']),
  'getAdminThreadForUser' : IDL.Func(
      [UserId],
      [IDL.Vec(AdminMessagePublic)],
      ['query'],
    ),
  'getAllReports' : IDL.Func([], [IDL.Vec(ReportPublic)], ['query']),
  'getApprovedReports' : IDL.Func([], [IDL.Vec(ReportPublic)], ['query']),
  'getBadgeMetadata' : IDL.Func([], [IDL.Vec(BadgeMetadata)], ['query']),
  'getChatHistory' : IDL.Func(
      [UserId],
      [IDL.Vec(ChatMessagePublic)],
      ['query'],
    ),
  'getChatList' : IDL.Func([], [IDL.Vec(ChatPreview)], ['query']),
  'getHeatmapData' : IDL.Func([], [IDL.Vec(HeatmapPoint)], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getMyAdminThread' : IDL.Func([], [IDL.Vec(AdminMessagePublic)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], ['query']),
  'getMyRank' : IDL.Func([], [IDL.Nat], ['query']),
  'getReport' : IDL.Func([ReportId], [IDL.Opt(ReportPublic)], ['query']),
  'getReportsByUser' : IDL.Func([UserId], [IDL.Vec(ReportPublic)], ['query']),
  'getUnreadCount' : IDL.Func([UserId], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [UserId],
      [IDL.Opt(UserProfilePublic)],
      ['query'],
    ),
  'markAdminMessagesRead' : IDL.Func([UserId], [], []),
  'markChatMessagesRead' : IDL.Func([UserId], [], []),
  'registerProfile' : IDL.Func([IDL.Text], [UserProfilePublic], []),
  'sendChatMessage' : IDL.Func([UserId, IDL.Text], [MessageId], []),
  'sendMessageToAdmin' : IDL.Func([IDL.Text], [MessageId], []),
  'submitReport' : IDL.Func([SubmitReportArgs], [ReportId], []),
  'updateAvatar' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Bool], []),
  'updateReportStatus' : IDL.Func([ReportId, ReportStatus], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Principal;
  const MessageId = IDL.Nat;
  const Timestamp = IDL.Int;
  const AdminMessagePublic = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'isRead' : IDL.Bool,
    'sender' : UserId,
    'sentAt' : Timestamp,
    'isAdminReply' : IDL.Bool,
  });
  const ReportId = IDL.Nat;
  const ReportStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'pending' : IDL.Null,
    'approved' : IDL.Null,
  });
  const ReportCategory = IDL.Variant({
    'other' : IDL.Null,
    'garbage' : IDL.Null,
    'unsafe' : IDL.Null,
    'pollution' : IDL.Null,
  });
  const ReportPublic = IDL.Record({
    'id' : ReportId,
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'status' : ReportStatus,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'photoUrl' : IDL.Text,
    'category' : ReportCategory,
    'reporter' : UserId,
  });
  const BadgeId = IDL.Variant({
    'pioneer' : IDL.Null,
    'hundred_reports' : IDL.Null,
    'ten_reports' : IDL.Null,
    'first_report' : IDL.Null,
    'fifty_reports' : IDL.Null,
    'eco_warrior' : IDL.Null,
  });
  const BadgeMetadata = IDL.Record({
    'id' : BadgeId,
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'milestone' : IDL.Text,
  });
  const ChatId = IDL.Text;
  const ChatMessagePublic = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'isRead' : IDL.Bool,
    'sender' : UserId,
    'sentAt' : Timestamp,
    'chatId' : ChatId,
  });
  const ChatPreview = IDL.Record({
    'lastMessageAt' : Timestamp,
    'otherUsername' : IDL.Text,
    'otherUserId' : UserId,
    'lastMessage' : IDL.Text,
    'unreadCount' : IDL.Nat,
    'chatId' : ChatId,
  });
  const HeatmapPoint = IDL.Record({
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'weight' : IDL.Nat,
  });
  const LeaderboardEntry = IDL.Record({
    'username' : IDL.Text,
    'userId' : UserId,
    'rank' : IDL.Nat,
    'badgeCount' : IDL.Nat,
    'points' : IDL.Nat,
  });
  const UserProfilePublic = IDL.Record({
    'id' : UserId,
    'reportCount' : IDL.Nat,
    'username' : IDL.Text,
    'badges' : IDL.Vec(BadgeId),
    'joinedAt' : Timestamp,
    'avatarUrl' : IDL.Opt(IDL.Text),
    'points' : IDL.Nat,
  });
  const SubmitReportArgs = IDL.Record({
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'description' : IDL.Text,
    'photoUrl' : IDL.Text,
    'category' : ReportCategory,
  });
  
  return IDL.Service({
    'adminReply' : IDL.Func([UserId, IDL.Text], [MessageId], []),
    'getAdminInbox' : IDL.Func([], [IDL.Vec(UserId)], ['query']),
    'getAdminThreadForUser' : IDL.Func(
        [UserId],
        [IDL.Vec(AdminMessagePublic)],
        ['query'],
      ),
    'getAllReports' : IDL.Func([], [IDL.Vec(ReportPublic)], ['query']),
    'getApprovedReports' : IDL.Func([], [IDL.Vec(ReportPublic)], ['query']),
    'getBadgeMetadata' : IDL.Func([], [IDL.Vec(BadgeMetadata)], ['query']),
    'getChatHistory' : IDL.Func(
        [UserId],
        [IDL.Vec(ChatMessagePublic)],
        ['query'],
      ),
    'getChatList' : IDL.Func([], [IDL.Vec(ChatPreview)], ['query']),
    'getHeatmapData' : IDL.Func([], [IDL.Vec(HeatmapPoint)], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getMyAdminThread' : IDL.Func([], [IDL.Vec(AdminMessagePublic)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], ['query']),
    'getMyRank' : IDL.Func([], [IDL.Nat], ['query']),
    'getReport' : IDL.Func([ReportId], [IDL.Opt(ReportPublic)], ['query']),
    'getReportsByUser' : IDL.Func([UserId], [IDL.Vec(ReportPublic)], ['query']),
    'getUnreadCount' : IDL.Func([UserId], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [UserId],
        [IDL.Opt(UserProfilePublic)],
        ['query'],
      ),
    'markAdminMessagesRead' : IDL.Func([UserId], [], []),
    'markChatMessagesRead' : IDL.Func([UserId], [], []),
    'registerProfile' : IDL.Func([IDL.Text], [UserProfilePublic], []),
    'sendChatMessage' : IDL.Func([UserId, IDL.Text], [MessageId], []),
    'sendMessageToAdmin' : IDL.Func([IDL.Text], [MessageId], []),
    'submitReport' : IDL.Func([SubmitReportArgs], [ReportId], []),
    'updateAvatar' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Bool], []),
    'updateReportStatus' : IDL.Func([ReportId, ReportStatus], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };