/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminMessagePublic {
  'id' : MessageId,
  'content' : string,
  'isRead' : boolean,
  'sender' : UserId,
  'sentAt' : Timestamp,
  'isAdminReply' : boolean,
}
export type BadgeId = { 'pioneer' : null } |
  { 'hundred_reports' : null } |
  { 'ten_reports' : null } |
  { 'first_report' : null } |
  { 'fifty_reports' : null } |
  { 'eco_warrior' : null };
export interface BadgeMetadata {
  'id' : BadgeId,
  'icon' : string,
  'name' : string,
  'milestone' : string,
}
export type ChatId = string;
export interface ChatMessagePublic {
  'id' : MessageId,
  'content' : string,
  'isRead' : boolean,
  'sender' : UserId,
  'sentAt' : Timestamp,
  'chatId' : ChatId,
}
export interface ChatPreview {
  'lastMessageAt' : Timestamp,
  'otherUsername' : string,
  'otherUserId' : UserId,
  'lastMessage' : string,
  'unreadCount' : bigint,
  'chatId' : ChatId,
}
export interface HeatmapPoint {
  'lat' : number,
  'lng' : number,
  'weight' : bigint,
}
export interface LeaderboardEntry {
  'username' : string,
  'userId' : UserId,
  'rank' : bigint,
  'badgeCount' : bigint,
  'points' : bigint,
}
export type MessageId = bigint;
export type ReportCategory = { 'other' : null } |
  { 'garbage' : null } |
  { 'unsafe' : null } |
  { 'pollution' : null };
export type ReportId = bigint;
export interface ReportPublic {
  'id' : ReportId,
  'lat' : number,
  'lng' : number,
  'status' : ReportStatus,
  'createdAt' : Timestamp,
  'description' : string,
  'photoUrl' : string,
  'category' : ReportCategory,
  'reporter' : UserId,
}
export type ReportStatus = { 'resolved' : null } |
  { 'pending' : null } |
  { 'approved' : null };
export interface SubmitReportArgs {
  'lat' : number,
  'lng' : number,
  'description' : string,
  'photoUrl' : string,
  'category' : ReportCategory,
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfilePublic {
  'id' : UserId,
  'reportCount' : bigint,
  'username' : string,
  'badges' : Array<BadgeId>,
  'joinedAt' : Timestamp,
  'avatarUrl' : [] | [string],
  'points' : bigint,
}
export interface _SERVICE {
  'adminReply' : ActorMethod<[UserId, string], MessageId>,
  'getAdminInbox' : ActorMethod<[], Array<UserId>>,
  'getAdminThreadForUser' : ActorMethod<[UserId], Array<AdminMessagePublic>>,
  'getAllReports' : ActorMethod<[], Array<ReportPublic>>,
  'getApprovedReports' : ActorMethod<[], Array<ReportPublic>>,
  'getBadgeMetadata' : ActorMethod<[], Array<BadgeMetadata>>,
  'getChatHistory' : ActorMethod<[UserId], Array<ChatMessagePublic>>,
  'getChatList' : ActorMethod<[], Array<ChatPreview>>,
  'getHeatmapData' : ActorMethod<[], Array<HeatmapPoint>>,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getMyAdminThread' : ActorMethod<[], Array<AdminMessagePublic>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfilePublic]>,
  'getMyRank' : ActorMethod<[], bigint>,
  'getReport' : ActorMethod<[ReportId], [] | [ReportPublic]>,
  'getReportsByUser' : ActorMethod<[UserId], Array<ReportPublic>>,
  'getUnreadCount' : ActorMethod<[UserId], bigint>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfilePublic]>,
  'markAdminMessagesRead' : ActorMethod<[UserId], undefined>,
  'markChatMessagesRead' : ActorMethod<[UserId], undefined>,
  'registerProfile' : ActorMethod<[string], UserProfilePublic>,
  'sendChatMessage' : ActorMethod<[UserId, string], MessageId>,
  'sendMessageToAdmin' : ActorMethod<[string], MessageId>,
  'submitReport' : ActorMethod<[SubmitReportArgs], ReportId>,
  'updateAvatar' : ActorMethod<[[] | [string]], boolean>,
  'updateReportStatus' : ActorMethod<[ReportId, ReportStatus], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];