/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LeaderboardEntry {
    username: string;
    userId: UserId;
    rank: bigint;
    badgeCount: bigint;
    points: bigint;
}
export type Timestamp = bigint;
export type ChatId = string;
export interface BadgeMetadata {
    id: BadgeId;
    icon: string;
    name: string;
    milestone: string;
}
export interface UserProfilePublic {
    id: UserId;
    reportCount: bigint;
    username: string;
    badges: Array<BadgeId>;
    joinedAt: Timestamp;
    avatarUrl?: string;
    points: bigint;
}
export type UserId = Principal;
export type ReportId = bigint;
export interface ReportPublic {
    id: ReportId;
    lat: number;
    lng: number;
    status: ReportStatus;
    createdAt: Timestamp;
    description: string;
    photoUrl: string;
    category: ReportCategory;
    reporter: UserId;
}
export type MessageId = bigint;
export interface HeatmapPoint {
    lat: number;
    lng: number;
    weight: bigint;
}
export interface SubmitReportArgs {
    lat: number;
    lng: number;
    description: string;
    photoUrl: string;
    category: ReportCategory;
}
export interface ChatPreview {
    lastMessageAt: Timestamp;
    otherUsername: string;
    otherUserId: UserId;
    lastMessage: string;
    unreadCount: bigint;
    chatId: ChatId;
}
export interface ChatMessagePublic {
    id: MessageId;
    content: string;
    isRead: boolean;
    sender: UserId;
    sentAt: Timestamp;
    chatId: ChatId;
}
export interface AdminMessagePublic {
    id: MessageId;
    content: string;
    isRead: boolean;
    sender: UserId;
    sentAt: Timestamp;
    isAdminReply: boolean;
}
export enum BadgeId {
    pioneer = "pioneer",
    hundred_reports = "hundred_reports",
    ten_reports = "ten_reports",
    first_report = "first_report",
    fifty_reports = "fifty_reports",
    eco_warrior = "eco_warrior"
}
export enum ReportCategory {
    other = "other",
    garbage = "garbage",
    unsafe = "unsafe",
    pollution = "pollution"
}
export enum ReportStatus {
    resolved = "resolved",
    pending = "pending",
    approved = "approved"
}
export interface backendInterface {
    adminReply(targetUserId: UserId, content: string): Promise<MessageId>;
    getAdminInbox(): Promise<Array<UserId>>;
    getAdminThreadForUser(userId: UserId): Promise<Array<AdminMessagePublic>>;
    getAllReports(): Promise<Array<ReportPublic>>;
    getApprovedReports(): Promise<Array<ReportPublic>>;
    getBadgeMetadata(): Promise<Array<BadgeMetadata>>;
    getChatHistory(otherUserId: UserId): Promise<Array<ChatMessagePublic>>;
    getChatList(): Promise<Array<ChatPreview>>;
    getHeatmapData(): Promise<Array<HeatmapPoint>>;
    getLeaderboard(): Promise<Array<LeaderboardEntry>>;
    getMyAdminThread(): Promise<Array<AdminMessagePublic>>;
    getMyProfile(): Promise<UserProfilePublic | null>;
    getMyRank(): Promise<bigint>;
    getReport(reportId: ReportId): Promise<ReportPublic | null>;
    getReportsByUser(userId: UserId): Promise<Array<ReportPublic>>;
    getUnreadCount(otherUserId: UserId): Promise<bigint>;
    getUserProfile(userId: UserId): Promise<UserProfilePublic | null>;
    markAdminMessagesRead(userId: UserId): Promise<void>;
    markChatMessagesRead(otherUserId: UserId): Promise<void>;
    registerProfile(username: string): Promise<UserProfilePublic>;
    sendChatMessage(recipient: UserId, content: string): Promise<MessageId>;
    sendMessageToAdmin(content: string): Promise<MessageId>;
    submitReport(args: SubmitReportArgs): Promise<ReportId>;
    updateAvatar(avatarUrl: string | null): Promise<boolean>;
    updateReportStatus(reportId: ReportId, status: ReportStatus): Promise<boolean>;
}
import type { BadgeId as _BadgeId, BadgeMetadata as _BadgeMetadata, ReportCategory as _ReportCategory, ReportId as _ReportId, ReportPublic as _ReportPublic, ReportStatus as _ReportStatus, SubmitReportArgs as _SubmitReportArgs, Timestamp as _Timestamp, UserId as _UserId, UserProfilePublic as _UserProfilePublic } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async adminReply(arg0: UserId, arg1: string): Promise<MessageId> {
        if (this.processError) {
            try {
                const result = await this.actor.adminReply(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminReply(arg0, arg1);
            return result;
        }
    }
    async getAdminInbox(): Promise<Array<UserId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminInbox();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminInbox();
            return result;
        }
    }
    async getAdminThreadForUser(arg0: UserId): Promise<Array<AdminMessagePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminThreadForUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminThreadForUser(arg0);
            return result;
        }
    }
    async getAllReports(): Promise<Array<ReportPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReports();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReports();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApprovedReports(): Promise<Array<ReportPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApprovedReports();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApprovedReports();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBadgeMetadata(): Promise<Array<BadgeMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBadgeMetadata();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBadgeMetadata();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChatHistory(arg0: UserId): Promise<Array<ChatMessagePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatHistory(arg0);
            return result;
        }
    }
    async getChatList(): Promise<Array<ChatPreview>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatList();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatList();
            return result;
        }
    }
    async getHeatmapData(): Promise<Array<HeatmapPoint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHeatmapData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHeatmapData();
            return result;
        }
    }
    async getLeaderboard(): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard();
            return result;
        }
    }
    async getMyAdminThread(): Promise<Array<AdminMessagePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyAdminThread();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyAdminThread();
            return result;
        }
    }
    async getMyProfile(): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyRank(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRank();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRank();
            return result;
        }
    }
    async getReport(arg0: ReportId): Promise<ReportPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReport(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReport(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReportsByUser(arg0: UserId): Promise<Array<ReportPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReportsByUser(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReportsByUser(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnreadCount(arg0: UserId): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadCount(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: UserId): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async markAdminMessagesRead(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAdminMessagesRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAdminMessagesRead(arg0);
            return result;
        }
    }
    async markChatMessagesRead(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markChatMessagesRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markChatMessagesRead(arg0);
            return result;
        }
    }
    async registerProfile(arg0: string): Promise<UserProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.registerProfile(arg0);
                return from_candid_UserProfilePublic_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerProfile(arg0);
            return from_candid_UserProfilePublic_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendChatMessage(arg0: UserId, arg1: string): Promise<MessageId> {
        if (this.processError) {
            try {
                const result = await this.actor.sendChatMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendChatMessage(arg0, arg1);
            return result;
        }
    }
    async sendMessageToAdmin(arg0: string): Promise<MessageId> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessageToAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessageToAdmin(arg0);
            return result;
        }
    }
    async submitReport(arg0: SubmitReportArgs): Promise<ReportId> {
        if (this.processError) {
            try {
                const result = await this.actor.submitReport(to_candid_SubmitReportArgs_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitReport(to_candid_SubmitReportArgs_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateAvatar(arg0: string | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAvatar(to_candid_opt_n23(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAvatar(to_candid_opt_n23(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateReportStatus(arg0: ReportId, arg1: ReportStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReportStatus(arg0, to_candid_ReportStatus_n24(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReportStatus(arg0, to_candid_ReportStatus_n24(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_BadgeId_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BadgeId): BadgeId {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_BadgeMetadata_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BadgeMetadata): BadgeMetadata {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_ReportCategory_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReportCategory): ReportCategory {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_ReportPublic_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReportPublic): ReportPublic {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_ReportStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReportStatus): ReportStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfilePublic_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfilePublic): UserProfilePublic {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfilePublic]): UserProfilePublic | null {
    return value.length === 0 ? null : from_candid_UserProfilePublic_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ReportPublic]): ReportPublic | null {
    return value.length === 0 ? null : from_candid_ReportPublic_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _BadgeId;
    icon: string;
    name: string;
    milestone: string;
}): {
    id: BadgeId;
    icon: string;
    name: string;
    milestone: string;
} {
    return {
        id: from_candid_BadgeId_n11(_uploadFile, _downloadFile, value.id),
        icon: value.icon,
        name: value.name,
        milestone: value.milestone
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    reportCount: bigint;
    username: string;
    badges: Array<_BadgeId>;
    joinedAt: _Timestamp;
    avatarUrl: [] | [string];
    points: bigint;
}): {
    id: UserId;
    reportCount: bigint;
    username: string;
    badges: Array<BadgeId>;
    joinedAt: Timestamp;
    avatarUrl?: string;
    points: bigint;
} {
    return {
        id: value.id,
        reportCount: value.reportCount,
        username: value.username,
        badges: from_candid_vec_n16(_uploadFile, _downloadFile, value.badges),
        joinedAt: value.joinedAt,
        avatarUrl: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.avatarUrl)),
        points: value.points
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ReportId;
    lat: number;
    lng: number;
    status: _ReportStatus;
    createdAt: _Timestamp;
    description: string;
    photoUrl: string;
    category: _ReportCategory;
    reporter: _UserId;
}): {
    id: ReportId;
    lat: number;
    lng: number;
    status: ReportStatus;
    createdAt: Timestamp;
    description: string;
    photoUrl: string;
    category: ReportCategory;
    reporter: UserId;
} {
    return {
        id: value.id,
        lat: value.lat,
        lng: value.lng,
        status: from_candid_ReportStatus_n4(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        description: value.description,
        photoUrl: value.photoUrl,
        category: from_candid_ReportCategory_n6(_uploadFile, _downloadFile, value.category),
        reporter: value.reporter
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pioneer: null;
} | {
    hundred_reports: null;
} | {
    ten_reports: null;
} | {
    first_report: null;
} | {
    fifty_reports: null;
} | {
    eco_warrior: null;
}): BadgeId {
    return "pioneer" in value ? BadgeId.pioneer : "hundred_reports" in value ? BadgeId.hundred_reports : "ten_reports" in value ? BadgeId.ten_reports : "first_report" in value ? BadgeId.first_report : "fifty_reports" in value ? BadgeId.fifty_reports : "eco_warrior" in value ? BadgeId.eco_warrior : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resolved: null;
} | {
    pending: null;
} | {
    approved: null;
}): ReportStatus {
    return "resolved" in value ? ReportStatus.resolved : "pending" in value ? ReportStatus.pending : "approved" in value ? ReportStatus.approved : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    garbage: null;
} | {
    unsafe: null;
} | {
    pollution: null;
}): ReportCategory {
    return "other" in value ? ReportCategory.other : "garbage" in value ? ReportCategory.garbage : "unsafe" in value ? ReportCategory.unsafe : "pollution" in value ? ReportCategory.pollution : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ReportPublic>): Array<ReportPublic> {
    return value.map((x)=>from_candid_ReportPublic_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BadgeId>): Array<BadgeId> {
    return value.map((x)=>from_candid_BadgeId_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BadgeMetadata>): Array<BadgeMetadata> {
    return value.map((x)=>from_candid_BadgeMetadata_n9(_uploadFile, _downloadFile, x));
}
function to_candid_ReportCategory_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportCategory): _ReportCategory {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_ReportStatus_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportStatus): _ReportStatus {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_SubmitReportArgs_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubmitReportArgs): _SubmitReportArgs {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lat: number;
    lng: number;
    description: string;
    photoUrl: string;
    category: ReportCategory;
}): {
    lat: number;
    lng: number;
    description: string;
    photoUrl: string;
    category: _ReportCategory;
} {
    return {
        lat: value.lat,
        lng: value.lng,
        description: value.description,
        photoUrl: value.photoUrl,
        category: to_candid_ReportCategory_n21(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportCategory): {
    other: null;
} | {
    garbage: null;
} | {
    unsafe: null;
} | {
    pollution: null;
} {
    return value == ReportCategory.other ? {
        other: null
    } : value == ReportCategory.garbage ? {
        garbage: null
    } : value == ReportCategory.unsafe ? {
        unsafe: null
    } : value == ReportCategory.pollution ? {
        pollution: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportStatus): {
    resolved: null;
} | {
    pending: null;
} | {
    approved: null;
} {
    return value == ReportStatus.resolved ? {
        resolved: null
    } : value == ReportStatus.pending ? {
        pending: null
    } : value == ReportStatus.approved ? {
        approved: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
